//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBQ.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WindowLeft {
            get {
                return ((double)(this["WindowLeft"]));
            }
            set {
                this["WindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WindowTop {
            get {
                return ((double)(this["WindowTop"]));
            }
            set {
                this["WindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bbecweb:8011/ProductQueues.xml")]
        public string ProductQueues {
            get {
                return ((string)(this["ProductQueues"]));
            }
            set {
                this["ProductQueues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bbecweb:8011/QueueDetails.xml")]
        public string QueueDetails {
            get {
                return ((string)(this["QueueDetails"]));
            }
            set {
                this["QueueDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bbecweb:8011/Product.xml")]
        public string ProductPath {
            get {
                return ((string)(this["ProductPath"]));
            }
            set {
                this["ProductPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Media.SolidColorBrush InactiveQueueBG {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["InactiveQueueBG"]));
            }
            set {
                this["InactiveQueueBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Media.SolidColorBrush InactiveQueueFG {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["InactiveQueueFG"]));
            }
            set {
                this["InactiveQueueFG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Media.SolidColorBrush InactiveCallTypeBG {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["InactiveCallTypeBG"]));
            }
            set {
                this["InactiveCallTypeBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Media.SolidColorBrush InactiveCallTypeFG {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["InactiveCallTypeFG"]));
            }
            set {
                this["InactiveCallTypeFG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Media.SolidColorBrush ActiveQueueBG {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ActiveQueueBG"]));
            }
            set {
                this["ActiveQueueBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Media.SolidColorBrush ActiveQueueFG {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ActiveQueueFG"]));
            }
            set {
                this["ActiveQueueFG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Media.SolidColorBrush ActiveCallTypeBG {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ActiveCallTypeBG"]));
            }
            set {
                this["ActiveCallTypeBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Media.SolidColorBrush ActiveCallTypeFG {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ActiveCallTypeFG"]));
            }
            set {
                this["ActiveCallTypeFG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Media.SolidColorBrush InactiveApplicationBackground {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["InactiveApplicationBackground"]));
            }
            set {
                this["InactiveApplicationBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PublicKey {
            get {
                return ((string)(this["PublicKey"]));
            }
            set {
                this["PublicKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NewInstall {
            get {
                return ((bool)(this["NewInstall"]));
            }
            set {
                this["NewInstall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Media.SolidColorBrush ExtendedQueueBG {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ExtendedQueueBG"]));
            }
            set {
                this["ExtendedQueueBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Media.SolidColorBrush ExtendedQueueFG {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ExtendedQueueFG"]));
            }
            set {
                this["ExtendedQueueFG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Media.SolidColorBrush ExtendedCallTypeBG {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ExtendedCallTypeBG"]));
            }
            set {
                this["ExtendedCallTypeBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Media.SolidColorBrush ExtendedCallTypeFG {
            get {
                return ((global::System.Windows.Media.SolidColorBrush)(this["ExtendedCallTypeFG"]));
            }
            set {
                this["ExtendedCallTypeFG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int SecondsTillExtended {
            get {
                return ((int)(this["SecondsTillExtended"]));
            }
            set {
                this["SecondsTillExtended"] = value;
            }
        }
    }
}
